---
title: "DataCleansing"
author: "Martyna Ignaczak"
date: "2024-04-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dlookr)
library(editrules)
library(VIM)
library(deducorrect)
library(ISLR) 
library(naniar)
library(mice)
library(ggplot2)
library(dplyr)
```

## Sample data


```{r include=FALSE}
# Load necessary libraries
library(tidyverse)

# Set seed for reproducibility
set.seed(123)

# Generate sample data
n <- 1000  # Number of observations

# Age between 18 and 90
age <- sample(18:90, n, replace = TRUE)

# Introduce errors in age column
age[sample(1:n, 50)] <- "InvalidAge"

# Workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked
workclass <- sample(c("Private", "Self-emp-not-inc", "Self-emp-inc", "Federal-gov", "Local-gov", "State-gov", "Without-pay", "Never-worked"), n, replace = TRUE)

# Introduce missing values in workclass column
workclass[sample(1:n, 50)] <- NA

# Education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool
education <- sample(c("Bachelors", "Some-college", "11th", "HS-grad", "Prof-school", "Assoc-acdm", "Assoc-voc", "9th", "7th-8th", "12th", "Masters", "1st-4th", "10th", "Doctorate", "5th-6th", "Preschool"), n, replace = TRUE)

# Introduce inconsistencies in education column
education[sample(1:n, 50)] <- "InvalidEducation"

# Education Number: 1-16
education_num <- sample(1:16, n, replace = TRUE)

# Marital Status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse
marital_status <- sample(c("Married-civ-spouse", "Divorced", "Never-married", "Separated", "Widowed", "Married-spouse-absent", "Married-AF-spouse"), n, replace = TRUE)

# Introduce missing values in marital_status column
marital_status[sample(1:n, 50)] <- NA

# Occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces
occupation <- sample(c("Tech-support", "Craft-repair", "Other-service", "Sales", "Exec-managerial", "Prof-specialty", "Handlers-cleaners", "Machine-op-inspct", "Adm-clerical", "Farming-fishing", "Transport-moving", "Priv-house-serv", "Protective-serv", "Armed-Forces"), n, replace = TRUE)

# Introduce errors in occupation column
occupation[sample(1:n, 50)] <- "InvalidOccupation"

# Relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried
relationship <- sample(c("Wife", "Own-child", "Husband", "Not-in-family", "Other-relative", "Unmarried"), n, replace = TRUE)

# Introduce missing values in relationship column
relationship[sample(1:n, 50)] <- NA

# Race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black
race <- sample(c("White", "Asian-Pac-Islander", "Amer-Indian-Eskimo", "Other", "Black"), n, replace = TRUE)

# Introduce inconsistencies in race column
race[sample(1:n, 50)] <- "InvalidRace"

# Sex: Female, Male
sex <- sample(c("Female", "Male"), n, replace = TRUE)

# Introduce missing values in sex column
sex[sample(1:n, 50)] <- NA

# Capital Gain: 0-99999
capital_gain <- sample(0:99999, n, replace = TRUE)

capital_gain_true <- capital_gain

# Introduce errors in capital_gain column
capital_gain[sample(1:n, 50)] <- -999

# Capital Loss: 0-99999
capital_loss <- sample(0:99999, n, replace = TRUE)

capital_loss_true <- capital_loss

# Introduce errors in capital_loss column
capital_loss[sample(1:n, 50)] <- -999

# Hours per week: 1-99
hours_per_week <- sample(1:99, n, replace = TRUE)

hours_per_week_true <- hours_per_week

# Introduce missing values in hours_per_week column
hours_per_week[sample(1:n, 50)] <- NA

# Native country: United-States, Cambodia, England, ...
native_country <- sample(c("United-States", "Cambodia", "England", "Puerto-Rico", "Canada", "Germany", "Outlying-US(Guam-USVI-etc)", "India", "Japan", "Greece", "South", "China", "Cuba", "Iran", "Honduras", "Philippines", "Italy", "Poland", "Jamaica", "Vietnam", "Mexico", "Portugal", "Ireland", "France", "Dominican-Republic", "Laos", "Ecuador", "Taiwan", "Haiti", "Columbia", "Hungary", "Guatemala", "Nicaragua", "Scotland", "Thailand", "Yugoslavia", "El-Salvador", "Trinadad&Tobago", "Peru", "Hong", "Holand-Netherlands"), n, replace = TRUE)

# Introduce missing values in native_country column
native_country[sample(1:n, 50)] <- NA

# Income: <=50K, >50K
income <- sample(c("<=50K", ">50K"), n, replace = TRUE, prob = c(0.75, 0.25))

# Create dataframe
sample_dirty_dataset <- data.frame(age, workclass, education, education_num, marital_status, occupation, relationship, race, sex, capital_gain, capital_loss, hours_per_week, native_country, income)

# Print first few rows of the dataset
head(sample_dirty_dataset)

```

## Error correction
### Replacing errors in data set with missing values

```{r}

sample_dirty_dataset$age = ifelse(sample_dirty_dataset$age == "InvalidAge", NA, sample_dirty_dataset$age)

sample_dirty_dataset$occupation = ifelse(sample_dirty_dataset$occupation == "InvalidOccupation", NA, sample_dirty_dataset$occupation)

sample_dirty_dataset$capital_loss = ifelse(sample_dirty_dataset$capital_loss == -999, NA, sample_dirty_dataset$capital_loss)

sample_dirty_dataset$capital_gain = ifelse(sample_dirty_dataset$capital_gain == -999, NA, sample_dirty_dataset$capital_gain)

sample_dirty_dataset$race = ifelse(sample_dirty_dataset$race == "InvalidRace", NA, sample_dirty_dataset$race)

sample_dirty_dataset$education = ifelse(sample_dirty_dataset$education == "InvalidEducation", NA, sample_dirty_dataset$education)


```


## Handling inconsistencies


```{r}
inconsistencies_education <- sample_dirty_dataset$education %in% c("Bachelors", "11th")
sample_dirty_dataset$education[sample(1:n, 50)] <- "InvalidEducation"
sample_dirty_dataset$education[inconsistencies_education] <- "InvalidEducation"

inconsistencies_race <- sample_dirty_dataset$race %in% c("Other")
sample_dirty_dataset$race[sample(1:n, 50)] <- "InvalidRace"
sample_dirty_dataset$race[inconsistencies_race] <- "InvalidRace"

```

## Adressing missing values
### Quick overwiev of missing data

```{r}
#missing values before changes
gg_miss_var(sample_dirty_dataset,  show_pct = TRUE)
#places with missing data
vis_miss(sample_dirty_dataset)
```
### Handling missing numeric data

```{r}
# imput missing numeric data
sample_dirty_dataset <- complete(mice(sample_dirty_dataset, m = 1))

# now there is no missing data in these columns
vis_miss(sample_dirty_dataset)

# the mean of true data is similar to the mean of imput data
mean(sample_dirty_dataset$capital_gain)
mean(capital_gain_true)

mean(sample_dirty_dataset$capital_loss)
mean(capital_loss_true)

mean(sample_dirty_dataset$hours_per_week)
mean(hours_per_week_true)

```

### Handling other missing data

```{r}
# using mutate to adress and change data
sample_dirty_dataset <- mutate(sample_dirty_dataset, workclass = ifelse(is.na(workclass), "Private", workclass))

sample_dirty_dataset <- mutate(sample_dirty_dataset, relationship = ifelse(is.na(relationship), "Other-realtive", relationship))

sample_dirty_dataset <- mutate(sample_dirty_dataset, occupation = ifelse(is.na(occupation), "Other-service", occupation))

sample_dirty_dataset <- mutate(sample_dirty_dataset, race = ifelse(is.na(race), "Other", race))

# now there is no missing data in these columns
vis_miss(sample_dirty_dataset)

# using mutate to change data through conclusion
sample_dirty_dataset <- sample_dirty_dataset %>%
  mutate(sex = if_else(is.na(sex) & relationship == "Wife", "Male", sex, missing = sex))

sample_dirty_dataset <- sample_dirty_dataset %>%
  mutate(sex = if_else(is.na(sex) & relationship == "Husband", "Female", sex, missing = sex))

sample_dirty_dataset <- sample_dirty_dataset %>%
  mutate(sex = if_else(is.na(sex) & marital_status == "Widowed", "Female", sex, missing = sex))

# now there is less mising data in the column
vis_miss(sample_dirty_dataset)

#removing other data - they cannot be imputed
sample_dirty_dataset <- na.omit(sample_dirty_dataset)

#missing values removed

gg_miss_var(sample_dirty_dataset, show_pct = TRUE)

```